### PR TITLE
src/sparse: Fix supernodal sptrsv build with LayoutRight=ON

### PR DESCRIPTION
**Pull request by e10harvey**
Sorry for the formatting changes; I can back those out if you'd like. My pre-commit hook ran:
```bash
for FILE in $(git diff --cached --name-only)
do
        clang-format -i -style=file $FILE
	git add $FILE
done
```

### CODE REVIEW

**Comment by e10harvey** [comment]
@iyamazaki, Using this branch built with LayoutRight=ON and LayoutLeft=OFF shows:
```
$ ./KokkosKernels_sparse_serial --gtest_filter=*sptrsv*
Note: Google Test filter = *sptrsv*
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from serial
[ RUN      ] serial.sparse_sptrsv_double_int_int_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_double_int_int_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_double_int_size_t_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_double_int_size_t_TestExecSpace (2 ms)
[ RUN      ] serial.sparse_sptrsv_float_int_int_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_float_int_int_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_float_int_size_t_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_float_int_size_t_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_kokkos_complex_double_int_int_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_kokkos_complex_double_int_int_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_kokkos_complex_double_int_size_t_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_kokkos_complex_double_int_size_t_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_kokkos_complex_float_int_int_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_kokkos_complex_float_int_int_TestExecSpace (1 ms)
[ RUN      ] serial.sparse_sptrsv_kokkos_complex_float_int_size_t_TestExecSpace
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
Supernode Tri Solve SUCCESS
SUPERNODAL_DAG
[       OK ] serial.sparse_sptrsv_kokkos_complex_float_int_size_t_TestExecSpace (1 ms)
[----------] 8 tests from serial (9 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (9 ms total)
[  PASSED  ] 8 tests.
```

**Comment by iyamazaki** [comment]
Thank you, @e10harvey. Yes, this is because the unit-test takes each column as supernode, and we don't need to specify the matrix is upper/lower, for instance. I will modify the unit test to have a non-trivial supernode.

**Comment by e10harvey** [comment]
@iyamazaki, should we merge this to fix the link errors?

**Comment by iyamazaki** [comment]
Now, we require LayoutLeft. So, we are okay? And, this may fix the link errors, but we need more to support LayoutRight.

**Comment by e10harvey** [comment]
I think this should be merged in case someone wants to start working on supporting LayoutRight; this will put them a step closer.

**Comment by iyamazaki** [comment]
Thank you @e10harvey. I am running a test locally, just to make sure!! Right now, if we try to enable SUPERNODAL_SPTRSV without LayoutLeft, we should see an error message. But, I wonder if we can add comments somewhere in the codes, saying we only support default_layout = LayoutLeft.. I may forget..

**Comment by e10harvey** [comment]
> Right now, if we try to enable SUPERNODAL_SPTRSV without LayoutLeft, we should see an error message. But, I wonder if we can add comments somewhere in the codes, saying we only support default_layout = LayoutLeft.. I may forget..

I think the CMake check you added via https://github.com/kokkos/kokkos-kernels/pull/997/commits/88cb062e9caebf6a058ef0beeed9cbbc15937165 is clear but a comment would be nice.

**Comment by iyamazaki** [comment]
Hi, @e10harvey. My quick local unit-test passed. Do you want to add the comments before merging this?

**Comment by e10harvey** [comment]
No. I am ready to merge.

**Pull request merged**
